/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import java.awt.Image;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Meeoro
 */
public class PlayMenu extends javax.swing.JFrame {

    private MainMenu mainMenu;
    private GameWindow gameWindow;
    private String name1, name2, color1, color2;
    
    /** Creates new form PlayMenu */
    public PlayMenu(String name1, String name2, String color1, String color2) {
        initComponents();
        this.name1 = name1;
        this.name2 = name2;
        this.color1 = color1;
        this.color2 = color2;
        
        if (name1 != null) {
            player1Name.setText(name1);
        }
        if (name2 != null) {
            player2Name.setText(name2);
        }
        if (color1 != null) {
            player1ColorChooser.setSelectedItem(color1);
        }
        if (color2 != null) {
            player2ColorChooser.setSelectedItem(color2);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player1Text = new javax.swing.JLabel();
        player1NameText = new javax.swing.JLabel();
        player1Name = new javax.swing.JTextField();
        player1ColorText = new javax.swing.JLabel();
        player1ColorChooser = new javax.swing.JComboBox<>();
        player2Text = new javax.swing.JLabel();
        player2NameText = new javax.swing.JLabel();
        player2Name = new javax.swing.JTextField();
        player2ColorText = new javax.swing.JLabel();
        player2ColorChooser = new javax.swing.JComboBox<>();
        mapList = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        mapPic = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        mainMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        setSize(getPreferredSize());
        getContentPane().setLayout(null);

        player1Text.setText("Player 1:");
        getContentPane().add(player1Text);
        player1Text.setBounds(10, 10, 50, 16);

        player1NameText.setText("Name:");
        getContentPane().add(player1NameText);
        player1NameText.setBounds(80, 10, 50, 16);

        player1Name.setToolTipText("Enter your name");
        player1Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1NameActionPerformed(evt);
            }
        });
        getContentPane().add(player1Name);
        player1Name.setBounds(140, 10, 95, 22);

        player1ColorText.setText("Color:");
        getContentPane().add(player1ColorText);
        player1ColorText.setBounds(260, 10, 40, 16);

        player1ColorChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RED", "BLU", "GRN", "BLK", "WHT" }));
        player1ColorChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1ColorChooserActionPerformed(evt);
            }
        });
        getContentPane().add(player1ColorChooser);
        player1ColorChooser.setBounds(320, 10, 62, 22);

        player2Text.setText("Player 2:");
        getContentPane().add(player2Text);
        player2Text.setBounds(10, 50, 50, 16);

        player2NameText.setText("Name:");
        getContentPane().add(player2NameText);
        player2NameText.setBounds(80, 50, 50, 16);

        player2Name.setToolTipText("Enter your name");
        player2Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2NameActionPerformed(evt);
            }
        });
        getContentPane().add(player2Name);
        player2Name.setBounds(140, 50, 95, 22);

        player2ColorText.setText("Color:");
        getContentPane().add(player2ColorText);
        player2ColorText.setBounds(260, 50, 40, 16);

        player2ColorChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RED", "BLU", "GRN", "BLK", "WHT" }));
        player2ColorChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2ColorChooserActionPerformed(evt);
            }
        });
        getContentPane().add(player2ColorChooser);
        player2ColorChooser.setBounds(320, 50, 62, 22);

        mapList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tron", "sun", "black", "dark", "galactic", "lake" }));
        mapList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mapListItemStateChanged(evt);
            }
        });
        getContentPane().add(mapList);
        mapList.setBounds(160, 110, 70, 22);

        jLabel1.setText("Choose a map");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 110, 110, 20);

        mapPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/maps/tron.jpg"))); // NOI18N
        mapPic.setText("jLabel2");
        getContentPane().add(mapPic);
        mapPic.setBounds(70, 150, 130, 130);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startButton);
        startButton.setBounds(260, 160, 100, 40);

        mainMenuButton.setText("Main Menu");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mainMenuButton);
        mainMenuButton.setBounds(260, 240, 100, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void player1NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player1NameActionPerformed

    private void player1ColorChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1ColorChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player1ColorChooserActionPerformed

    private void player2NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player2NameActionPerformed

    private void player2ColorChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2ColorChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player2ColorChooserActionPerformed

    private void mapListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mapListItemStateChanged
        String text = mapList.getSelectedItem().toString();
        mapPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/maps/" + text + ".jpg")));;
    }//GEN-LAST:event_mapListItemStateChanged

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        String name1 = player1Name.getText();
        String name2 = player2Name.getText();
        String color1 = (String)player1ColorChooser.getSelectedItem();
        String color2 = (String)player2ColorChooser.getSelectedItem();
        String map = (String)mapList.getSelectedItem();
        try {
            gameWindow = new GameWindow(name1, name2, color1, color2, map);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PlayMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        mainMenu = new MainMenu();
        mainMenu.setVisible(true);
        mainMenu.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_mainMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayMenu("","","","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JComboBox<String> mapList;
    private javax.swing.JLabel mapPic;
    private javax.swing.JComboBox<String> player1ColorChooser;
    private javax.swing.JLabel player1ColorText;
    private javax.swing.JTextField player1Name;
    private javax.swing.JLabel player1NameText;
    private javax.swing.JLabel player1Text;
    private javax.swing.JComboBox<String> player2ColorChooser;
    private javax.swing.JLabel player2ColorText;
    private javax.swing.JTextField player2Name;
    private javax.swing.JLabel player2NameText;
    private javax.swing.JLabel player2Text;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables

    private Image getbgfromlist() {
        Image img = new ImageIcon("resources/maps/" + mapList.getDropTarget() + ".txt").getImage();
        return img;
    }

}
